name: file_change_notification
on:
  push:
    branches:
      - main
    paths:
      - ''
      - ''

jobs:
  hawk:
    name: hawk
    runs-on: ubuntu-latest

    steps:
    - name: CommitHawk
      uses: jesalg/commit-hawk-action@v1.1
      with:
        slack_webhook_url: ${{ secrets.STATUS_TEST_WEBHOOK_URL }}
        slack_message: 'Content of some important file were changed in main'